/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2_etapa3_joaofelipe_ianseki;

import javax.swing.JOptionPane;

/**
 *
 * @author joaof
 */
public class AlterarLavagem extends javax.swing.JFrame {

    /**
     * Creates new form AlterarLavagem
     */
    Lavar l;
    Gerenciadora g;
    public AlterarLavagem(Gerenciadora g) {
        initComponents();
        this.g = g;
        txtalterarlavagem_codlavagem.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnalterarl_voltar = new javax.swing.JButton();
        btnalterarl_mostrar = new javax.swing.JButton();
        btnalterarl_salvar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtalterarfun_idfun = new javax.swing.JTextField();
        txtalterarlavagem_idfun = new javax.swing.JTextField();
        txtalterarlavagem_tipolavagem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtalterarlavagem_codlavagem = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtalterarlavagem_horaentrada = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtalterarlavagem_horasaida = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtalterarlavagem_placacar = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnalterarl_voltar.setText("Voltar");
        btnalterarl_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarl_voltarActionPerformed(evt);
            }
        });

        btnalterarl_mostrar.setText("Mostrar dados");
        btnalterarl_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarl_mostrarActionPerformed(evt);
            }
        });

        btnalterarl_salvar.setText("Salvar");
        btnalterarl_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarl_salvarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Alterar Lavagem:");

        jLabel5.setText("Digite o Codigo de lavagem:");

        txtalterarfun_idfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalterarfun_idfunActionPerformed(evt);
            }
        });

        txtalterarlavagem_idfun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalterarlavagem_idfunActionPerformed(evt);
            }
        });

        jLabel7.setText("Código Lavagem:");

        jLabel2.setText("ID do funcionario que irá fazer o serviço:");

        try {
            txtalterarlavagem_horaentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtalterarlavagem_horaentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalterarlavagem_horaentradaActionPerformed(evt);
            }
        });

        jLabel3.setText("Placa  do carro para lavagem:");

        try {
            txtalterarlavagem_horasaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtalterarlavagem_horasaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalterarlavagem_horasaidaActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo lavagem:");

        try {
            txtalterarlavagem_placacar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtalterarlavagem_placacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalterarlavagem_placacarActionPerformed(evt);
            }
        });

        jLabel6.setText("Hora de entrada: ");

        jLabel8.setText("Previsão de hora de saída:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtalterarlavagem_horaentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtalterarlavagem_horasaida, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtalterarlavagem_placacar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(txtalterarlavagem_tipolavagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtalterarlavagem_codlavagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(27, 27, 27)
                                    .addComponent(txtalterarlavagem_idfun, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1)
                        .addGap(111, 156, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnalterarl_voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnalterarl_mostrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnalterarl_salvar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtalterarfun_idfun, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtalterarfun_idfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtalterarlavagem_idfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtalterarlavagem_placacar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalterarlavagem_tipolavagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtalterarlavagem_horaentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtalterarlavagem_horasaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtalterarlavagem_codlavagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnalterarl_voltar)
                    .addComponent(btnalterarl_mostrar)
                    .addComponent(btnalterarl_salvar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnalterarl_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarl_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnalterarl_voltarActionPerformed

    private void btnalterarl_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarl_mostrarActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(txtalterarfun_idfun.getText());
        l = g.buscarl(cod);

        if (l != null) {
            txtalterarlavagem_idfun.setText(String.valueOf(l.getID()));
            txtalterarlavagem_placacar.setText(l.getPlaca());
            txtalterarlavagem_tipolavagem.setText(l.getTipolavagem());
            txtalterarlavagem_horaentrada.setText(l.getHorasdeentrada());
            txtalterarlavagem_horasaida.setText(l.getHorasestimadas());
            txtalterarlavagem_codlavagem.setText(String.valueOf(l.getCodlavagem()));
            
        } else {
            JOptionPane.showMessageDialog(null, " Não existe!!!");
        }
    }//GEN-LAST:event_btnalterarl_mostrarActionPerformed

    private void btnalterarl_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarl_salvarActionPerformed
        // TODO add your handling code here:

        int cod = Integer.parseInt(txtalterarfun_idfun.getText());
        
        int idf = Integer.parseInt(txtalterarlavagem_idfun.getText());
        String placa = txtalterarlavagem_placacar.getText();
        String tipolavagem = txtalterarlavagem_tipolavagem.getText();
        String horae = txtalterarlavagem_horaentrada.getText();
        String horas = txtalterarlavagem_horasaida.getText();
        int codl = Integer.parseInt(txtalterarlavagem_codlavagem.getText());
        

        boolean verificar = g.alterarl(idf, placa, tipolavagem, horae, horas,codl);

        if (verificar == true) {
            JOptionPane.showMessageDialog(null, "Alterado com sucesso!!!!");
        } else
        JOptionPane.showMessageDialog(null, "Ocorreu um erro!!!!");
    }//GEN-LAST:event_btnalterarl_salvarActionPerformed

    private void txtalterarfun_idfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalterarfun_idfunActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtalterarfun_idfunActionPerformed

    private void txtalterarlavagem_horaentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalterarlavagem_horaentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalterarlavagem_horaentradaActionPerformed

    private void txtalterarlavagem_horasaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalterarlavagem_horasaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalterarlavagem_horasaidaActionPerformed

    private void txtalterarlavagem_placacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalterarlavagem_placacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalterarlavagem_placacarActionPerformed

    private void txtalterarlavagem_idfunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalterarlavagem_idfunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalterarlavagem_idfunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarLavagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AlterarLavagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnalterarl_mostrar;
    private javax.swing.JButton btnalterarl_salvar;
    private javax.swing.JButton btnalterarl_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtalterarfun_idfun;
    private javax.swing.JTextField txtalterarlavagem_codlavagem;
    private javax.swing.JFormattedTextField txtalterarlavagem_horaentrada;
    private javax.swing.JFormattedTextField txtalterarlavagem_horasaida;
    private javax.swing.JTextField txtalterarlavagem_idfun;
    private javax.swing.JFormattedTextField txtalterarlavagem_placacar;
    private javax.swing.JTextField txtalterarlavagem_tipolavagem;
    // End of variables declaration//GEN-END:variables
}
