
package tp2_etapa3_joaofelipe_ianseki;

import java.util.ArrayList;
import javax.swing.JOptionPane;


public class CadastrarCarro extends javax.swing.JFrame {

    Gerenciadora ge;

    public CadastrarCarro(Gerenciadora ge) {

        initComponents();
        setLocationRelativeTo(null);
        this.ge = ge;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcadastro_nomeclien = new javax.swing.JTextField();
        txtcadastro_nomecar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btncadastrarcar_cadastrar = new javax.swing.JButton();
        btncadastrar_voltar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btncadastrarcar_consultar = new javax.swing.JButton();
        txtcadastro_telcliente = new javax.swing.JFormattedTextField();
        txtcadastro_carplaca = new javax.swing.JFormattedTextField();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Cadastrar os carros:");

        txtcadastro_nomeclien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadastro_nomeclienActionPerformed(evt);
            }
        });

        txtcadastro_nomecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadastro_nomecarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do cliente:");

        jLabel4.setText("Nome do carro:");

        jLabel5.setText("Placa:");

        btncadastrarcar_cadastrar.setText("Cadastrar");
        btncadastrarcar_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarcar_cadastrarActionPerformed(evt);
            }
        });

        btncadastrar_voltar.setText("Voltar");
        btncadastrar_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrar_voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Telefone:");

        btncadastrarcar_consultar.setText("Consultar");
        btncadastrarcar_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarcar_consultarActionPerformed(evt);
            }
        });

        try {
            txtcadastro_telcliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcadastro_telcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadastro_telclienteActionPerformed(evt);
            }
        });

        try {
            txtcadastro_carplaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcadastro_carplaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcadastro_carplacaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btncadastrar_voltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncadastrarcar_consultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncadastrarcar_cadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtcadastro_telcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtcadastro_nomeclien, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcadastro_nomecar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcadastro_carplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcadastro_nomeclien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcadastro_telcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtcadastro_nomecar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtcadastro_carplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrarcar_cadastrar)
                    .addComponent(btncadastrar_voltar)
                    .addComponent(btncadastrarcar_consultar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcadastro_nomecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadastro_nomecarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadastro_nomecarActionPerformed
    
    
    public void verificaPlaca(String placa){
        
        ArrayList<Carro> car = ge.retornac();
        for(Carro c: car){
            if(c.getPlaca().equals(placa)){
                throw new PlacaInvalidException();
            }
        }
        
    }
    
    private void btncadastrarcar_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarcar_cadastrarActionPerformed
        try {
            
            
            String placa = txtcadastro_carplaca.getText();
            String nomecar = txtcadastro_nomecar.getText();
            String nomecli = txtcadastro_nomeclien.getText();
            String telefone = txtcadastro_telcliente.getText();
            
            verificaPlaca(placa);

            boolean resp = ge.cadastrarc(nomecli, nomecar, placa, telefone);

            if (resp == true) {
                txtcadastro_carplaca.setText("");
                txtcadastro_nomecar.setText("");
                txtcadastro_nomeclien.setText("");
                txtcadastro_telcliente.setText("");
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso!!!");
            } else {
                JOptionPane.showMessageDialog(null, " Não cadastrado!!!");
            }
            
        } catch (PlacaInvalidException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
      
        }
    }//GEN-LAST:event_btncadastrarcar_cadastrarActionPerformed

    private void btncadastrar_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrar_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_btncadastrar_voltarActionPerformed

    private void txtcadastro_nomeclienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadastro_nomeclienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadastro_nomeclienActionPerformed

    private void btncadastrarcar_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarcar_consultarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);                                         //some com a tela principal
        new ConsultarCarro(ge).setVisible(true);
    }//GEN-LAST:event_btncadastrarcar_consultarActionPerformed

    private void txtcadastro_telclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadastro_telclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadastro_telclienteActionPerformed

    private void txtcadastro_carplacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcadastro_carplacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcadastro_carplacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CadastrarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar_voltar;
    private javax.swing.JButton btncadastrarcar_cadastrar;
    private javax.swing.JButton btncadastrarcar_consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField txtcadastro_carplaca;
    private javax.swing.JTextField txtcadastro_nomecar;
    private javax.swing.JTextField txtcadastro_nomeclien;
    private javax.swing.JFormattedTextField txtcadastro_telcliente;
    // End of variables declaration//GEN-END:variables
}
