/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2_etapa3_joaofelipe_ianseki;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joaof
 */
public class ConsultarFuncionario extends javax.swing.JFrame {

    Gerenciadora ge;
    Funcionario func;

    public ConsultarFuncionario(Gerenciadora ge) {   
        initComponents();
        setLocationRelativeTo(null);
        this.ge = ge;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtconsultarfun_idfun = new javax.swing.JTextField();
        txtconsultarfun_nomefun = new javax.swing.JTextField();
        txtconsultarfun_cpffun = new javax.swing.JTextField();
        btnconsultarfun_voltar = new javax.swing.JButton();
        btnconsultarfun_consultar = new javax.swing.JButton();
        btnconsultarfun_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consultar funcionario:");

        jLabel2.setText("Digite o ID do funcionario para consultar:");

        jLabel3.setText("Nome do funcionario:");

        jLabel4.setText("CPF:");

        txtconsultarfun_nomefun.setEditable(false);
        txtconsultarfun_nomefun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsultarfun_nomefunActionPerformed(evt);
            }
        });

        txtconsultarfun_cpffun.setEditable(false);
        txtconsultarfun_cpffun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsultarfun_cpffunActionPerformed(evt);
            }
        });

        btnconsultarfun_voltar.setText("Voltar");
        btnconsultarfun_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarfun_voltarActionPerformed(evt);
            }
        });

        btnconsultarfun_consultar.setText("Consultar");
        btnconsultarfun_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarF(evt);
            }
        });

        btnconsultarfun_limpar.setText("Limpar");
        btnconsultarfun_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarfun_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtconsultarfun_idfun))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(btnconsultarfun_voltar))
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnconsultarfun_limpar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnconsultarfun_consultar))
                                    .addComponent(txtconsultarfun_cpffun)
                                    .addComponent(txtconsultarfun_nomefun)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtconsultarfun_idfun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtconsultarfun_nomefun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtconsultarfun_cpffun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultarfun_voltar)
                    .addComponent(btnconsultarfun_consultar)
                    .addComponent(btnconsultarfun_limpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarF(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarF
      int id = Integer.parseInt(txtconsultarfun_idfun.getText());
      func = ge.buscaFun(id);
      if(func !=null){
          txtconsultarfun_cpffun.setText(func.getCpf());
          txtconsultarfun_nomefun.setText(func.getNome()); 
          
      }
      else{
           JOptionPane.showMessageDialog(null, " Não existe!!!");
      }
        
    }//GEN-LAST:event_consultarF

    private void btnconsultarfun_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarfun_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnconsultarfun_voltarActionPerformed

    private void btnconsultarfun_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarfun_limparActionPerformed
        // TODO add your handling code here:
        txtconsultarfun_cpffun.setText("");
        txtconsultarfun_idfun.setText("");
        txtconsultarfun_nomefun.setText("");
    }//GEN-LAST:event_btnconsultarfun_limparActionPerformed

    private void txtconsultarfun_cpffunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsultarfun_cpffunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsultarfun_cpffunActionPerformed

    private void txtconsultarfun_nomefunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsultarfun_nomefunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsultarfun_nomefunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultarfun_consultar;
    private javax.swing.JButton btnconsultarfun_limpar;
    private javax.swing.JButton btnconsultarfun_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtconsultarfun_cpffun;
    private javax.swing.JTextField txtconsultarfun_idfun;
    private javax.swing.JTextField txtconsultarfun_nomefun;
    // End of variables declaration//GEN-END:variables
}
