/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp2_etapa3_joaofelipe_ianseki;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author joaof
 */
public class ConsultarCarro extends javax.swing.JFrame {
    Carro c;
    Gerenciadora ge;
    public ConsultarCarro(Gerenciadora ge) {
        initComponents();
        setLocationRelativeTo(null);
        this.ge = ge;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnconsultarcar_consultar = new javax.swing.JButton();
        btnconsultar_voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtcar_clientenome = new javax.swing.JTextField();
        txtcar_clitel = new javax.swing.JTextField();
        txtcar_nomecarro = new javax.swing.JTextField();
        btnconsultarcar_limpar = new javax.swing.JButton();
        txtconsultar_placa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Consultar carros:");

        btnconsultarcar_consultar.setText("Consultar");
        btnconsultarcar_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta(evt);
            }
        });

        btnconsultar_voltar.setText("Voltar");
        btnconsultar_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar_voltarActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite a placa para consultar os dados:");

        jLabel3.setText("Nome do cliente:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Nome do carro:");

        txtcar_clientenome.setEditable(false);
        txtcar_clientenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcar_clientenomeActionPerformed(evt);
            }
        });

        txtcar_clitel.setEditable(false);
        txtcar_clitel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcar_clitelActionPerformed(evt);
            }
        });

        txtcar_nomecarro.setEditable(false);
        txtcar_nomecarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcar_nomecarroActionPerformed(evt);
            }
        });

        btnconsultarcar_limpar.setText("Limpar");
        btnconsultarcar_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarcar_limparActionPerformed(evt);
            }
        });

        try {
            txtconsultar_placa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtconsultar_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconsultar_placaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(139, 139, 139)
                                        .addComponent(txtcar_nomecarro))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(27, 27, 27)
                                        .addComponent(txtconsultar_placa)))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnconsultar_voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnconsultarcar_limpar)
                                .addGap(18, 18, 18)
                                .addComponent(btnconsultarcar_consultar)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcar_clitel)
                            .addComponent(txtcar_clientenome))
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtconsultar_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcar_clientenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtcar_clitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcar_nomecarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultarcar_consultar)
                    .addComponent(btnconsultar_voltar)
                    .addComponent(btnconsultarcar_limpar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarcar_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarcar_limparActionPerformed
        // TODO add your handling code here:
        txtcar_clientenome.setText("");
        txtcar_clitel.setText("");
        txtcar_nomecarro.setText("");
        txtconsultar_placa.setText("");
        
        
    }//GEN-LAST:event_btnconsultarcar_limparActionPerformed

    private void txtcar_clientenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcar_clientenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcar_clientenomeActionPerformed

    private void txtcar_clitelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcar_clitelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcar_clitelActionPerformed

    private void txtcar_nomecarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcar_nomecarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcar_nomecarroActionPerformed

    private void consulta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta
        String nome  = txtcar_clientenome.getText();
        String nomeC = txtcar_nomecarro.getText();
        String clitel= txtcar_clitel.getText();   
        String placa = txtconsultar_placa.getText();
        c = ge.buscacar(placa);
      if(c !=null){
          txtcar_clientenome.setText(c.getNomecli());
          txtcar_clitel.setText(c.getTelefone());
          txtcar_nomecarro.setText(c.getNomecar());        
      }
      else{
           JOptionPane.showMessageDialog(null, " Não existe!!!");
      }
            
    }//GEN-LAST:event_consulta

    private void btnconsultar_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar_voltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_btnconsultar_voltarActionPerformed

    private void txtconsultar_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconsultar_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconsultar_placaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ConsultarCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultar_voltar;
    private javax.swing.JButton btnconsultarcar_consultar;
    private javax.swing.JButton btnconsultarcar_limpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcar_clientenome;
    private javax.swing.JTextField txtcar_clitel;
    private javax.swing.JTextField txtcar_nomecarro;
    private javax.swing.JFormattedTextField txtconsultar_placa;
    // End of variables declaration//GEN-END:variables
}
